---
title: "Project proposal"
author: "Leonardo Capitani and Francesco Pomati"
format: html
editor: visual
---

## Title 

Inferring and predicting plankton networks emergent properties in changing lakes

In this research project we aim to answer this open questions: 

1. To what extent do temperature, phosphorus and nitrogen levels have caused network emergent properties to vary?

2. How does invasive species presence/abundance have  influenced network emergent properties?

3. How will plankton network emergent properties change in the near future (next 5-10 years)? 

## Summary

Climate change, nutrient fluctuations and species invasions are fundamentally altering freshwater ecosystems; yet, their interactive effects on plankton community structure and pelagic food web stability remain poorly understood, hindering our ability to forecast essential ecosystem services. Here, we will investigate how warming temperatures and changing nutrient levels reshape ecological interaction networks in several temperate lakes, which provide recreation, fishing and drinking water to millions of people and have experienced eutrophication, climate change and biological invasions. Using long-term plankton monitoring data, we will apply the empirical dynamic modelling framework to reconstruct time-varying interaction networks and quantify species interaction strengths, connectance, and network stability. We hypothesise that plankton networks exhibit nonlinear responses to environmental drivers, with network reorganisation at critical temperature-nutrient thresholds or during the establishment of invasive species. Results corroborating hypotheses would demonstrate predictable network reorganisations and tipping points; disconfirming results would suggest stochastic patterns. Models will be forced by climatic scenarios to forecast future network properties and regime shifts, providing mechanistic understanding and evidence-based management strategies.

## Project team 

-   Dr. Francesco Pomati, Swiss Federal Institute of Aquatic Science and Technology (Eawag), Switzerland

-   Dr. Leonardo Capitani, Swiss Federal Institute of Aquatic Science and Technology (Eawag), Switzerland.

-   Research Assistant: Stefanie Merkli, Swiss Federal Institute of Aquatic Science and Technology (Eawag), Switzerland

## Collaborators

- Dr. Stephan Munch (smunch@ucsc.edu)
- Dr. Tanya Rogers (tanya.rogers@noaa.gov)
- Dr. Cheng-Han Tsai (tsaich@gs.ncku.edu.tw)
- ... to be annunced
